language: php
php:
  - 5.5
  - 5.4
  - 5.3
  - hhvm

before_script:
  - composer install --dev --prefer-source

env:
  - SYMFONY_VERSION=2.1.*
  - SYMFONY_VERSION=2.2.*
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.4.*
  - SYMFONY_VERSION=2.5.*
  - SYMFONY_VERSION=dev-master
